# Generated by Django 6.1.1 on 2026-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('spawn_interval_base', models.IntegerField(default=1000)),
                ('enemy_speed_base', models.IntegerField(default=100)),
                ('abates_para_vencer', models.IntegerField(default=15)),
                ('tem_chefe', models.BooleanField(default=False)),
                ('chefe_vida', models.IntegerField(default=0)),
            ],
        ),
    ]
