# Generated by Django 6.1.1 on 2026-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='nivel',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nivel',
            name='dificuldade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
