# Generated by Django 6.1.1 on 2026-09-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_alter_nivel_options_nivel_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('icone', models.CharField(default='🎁', max_length=10)),
                ('preco', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['preco'],
            },
        ),
    ]
