# Generated by Django 6.1.1 on 2026-09-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hance_tanque',
            field=models.FloatField(default=0.0, help_text='Probabilidade (0 a 1) de um inimigo comum spawnar como tanque neste nível'),
        ),
    ]
