# Generated by Django 6.1.1 on 2026-09-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0005_remove_item_hance_tanque_nivel_hance_tanque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel',
            old_name='hance_tanque',
            new_name='chance_tanque',
        ),
    ]
