# Generated by Django 6.1.1 on 2026-09-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0006_rename_hance_tanque_nivel_chance_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='fundo_chave',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('gelo', 'Gelo')], default='padrao', help_text='Precisa bater com uma chave cadastrada em FUNDOS_POR_CHAVE no Combate.js', max_length=50),
        ),
    ]
