# Generated by Django 6.1.1 on 2026-09-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0007_nivel_fundo_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='fundo_chave',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('noite', 'Noite')], default='padrao', help_text='Precisa bater com uma chave cadastrada em FUNDOS_POR_CHAVE no Combate.js', max_length=50),
        ),
    ]
