# Generated by Django 6.1.1 on 2026-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0008_alter_nivel_fundo_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='chance_rapido',
            field=models.FloatField(default=0.0, help_text='Probabilidade (0 a 1) de um inimigo comum spawnar como rápido neste nível'),
        ),
    ]
